export const Subjects = [
  "Historia de España",
  "Economía",
  "Lengua Castellana y Literatura",
  "Inglés",
  "Dibujo Técnico",
  "Matemáticas",
  "Latín",
  "Geografía",
  "Historia del Arte",
  "Biología",
  "Química",
  "Física",
  "Latín",
  "Filosofía",
];
